# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.217.4/containers/alpine/.devcontainer/base.Dockerfile

# [Choice] Alpine version: 3.14, 3.13, 3.12, 3.11
ARG VARIANT="latest"
#FROM ghcr.io/roueslibres1/runner-antora:${VARIANT}
FROM runner-antora:latest

# ** [Optional] Uncomment this section to install additional packages. **
# RUN apk update \
#     && apk add --no-cache <your-package-list-here>
