---
name: "pr-linter"

on:
  pull_request:

jobs:
  commits_checks:
    name: "Commits checks"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 0

      - name: "Check commit messages"
        uses: "docker://aevea/commitsar"
